;ini 파일 사용법
; 주석은 주로 ; 이나 #으로 사용가능
; data 는 key = value 형식으로 저장
[FILE_SETTINGS]
inventory_file = Mars_Base_Inventory_List.csv

[DATA_STRUCTURE]
;물질, 무게(g/cm ³), 비중, 강도, 가연성
headers = Substance,Weight (g/cm³),Specific Gravity,Strength,Flammability

[SORT_DATA_SETTINGS]
# 정렬 기준 컬럼을 명시
sort_target = Flammability
# 정렬 방식 (True: 내림차순, False: 오름차순)
sort_descending = True

[SEARCH_DATA_SETTINGS]
# 검색 기준 컬럼을 명시
search_target = Flammability
# 검색하려는 컬럼의 기준 값
search_baseline_value = 0.5